<Project>
  <PropertyGroup>
    <Version>1.2.7</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Peppermill is a fork of CSharpier, an opinionated code formatter for c#.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
